import type { MobilePlatform, NewsTopic, SourceTier } from '../types'

export type MobileSourceKind = 'html' | 'rss' | 'atom'

export interface MobileSourceConfig {
  topic: NewsTopic
  platform: MobilePlatform
  name: string
  url: string
  kind: MobileSourceKind
  sourceTier: SourceTier
  isOfficial: boolean
  limit?: number
}

export const MOBILE_SOURCES: MobileSourceConfig[] = [
  {
    topic: 'mobile',
    platform: 'ios',
    name: 'Apple Developer News',
    url: 'https://developer.apple.com/jp/news/',
    kind: 'html',
    sourceTier: 'official',
    isOfficial: true,
    limit: 8,
  },
  {
    topic: 'mobile',
    platform: 'ios',
    name: 'Apple Developer News EN',
    url: 'https://developer.apple.com/news/',
    kind: 'html',
    sourceTier: 'official',
    isOfficial: true,
    limit: 8,
  },
  {
    topic: 'mobile',
    platform: 'ios',
    name: 'Apple Developer News RSS',
    url: 'https://developer.apple.com/jp/news/rss/news.rss',
    kind: 'rss',
    sourceTier: 'official-rss',
    isOfficial: true,
    limit: 8,
  },
  {
    topic: 'mobile',
    platform: 'ios',
    name: 'Apple Developer News RSS EN',
    url: 'https://developer.apple.com/news/rss/news.rss',
    kind: 'rss',
    sourceTier: 'official-rss',
    isOfficial: true,
    limit: 8,
  },
  {
    topic: 'mobile',
    platform: 'ios',
    name: 'App Store Connect Release Notes',
    url: 'https://developer.apple.com/help/app-store-connect/release-notes/',
    kind: 'html',
    sourceTier: 'official',
    isOfficial: true,
    limit: 8,
  },
  {
    topic: 'mobile',
    platform: 'ios',
    name: 'Taisyo',
    url: 'http://taisy0.com/feed',
    kind: 'rss',
    sourceTier: 'community-rss',
    isOfficial: false,
    limit: 20,
  },
  {
    topic: 'mobile',
    platform: 'android',
    name: 'menthas',
    url: 'http://menthas.com/android/rss',
    kind: 'rss',
    sourceTier: 'community-rss',
    isOfficial: false,
    limit: 20,
  },
  {
    topic: 'mobile',
    platform: 'ios',
    name: 'menthas iOS',
    url: 'https://menthas.com/ios/rss',
    kind: 'rss',
    sourceTier: 'community-rss',
    isOfficial: false,
    limit: 20,
  },
  {
    topic: 'mobile',
    platform: 'android',
    name: 'Android Weekly',
    url: 'https://androidweekly.net/rss.xml',
    kind: 'rss',
    sourceTier: 'community-rss',
    isOfficial: false,
    limit: 20,
  },
  {
    topic: 'mobile',
    platform: 'ios',
    name: 'Swift with Majid',
    url: 'https://swiftwithmajid.com/feed.xml',
    kind: 'rss',
    sourceTier: 'community-rss',
    isOfficial: false,
    limit: 20,
  },
  {
    topic: 'mobile',
    platform: 'cross',
    name: 'Google Developers Japan',
    url: 'https://developers-jp.googleblog.com/',
    kind: 'html',
    sourceTier: 'official',
    isOfficial: true,
    limit: 8,
  },
  {
    topic: 'mobile',
    platform: 'android',
    name: 'Android Developers Blog',
    url: 'https://android-developers.googleblog.com/',
    kind: 'html',
    sourceTier: 'official',
    isOfficial: true,
    limit: 8,
  },
  {
    topic: 'mobile',
    platform: 'android',
    name: 'Android Developers Japan Blog',
    url: 'https://android-developers-jp.googleblog.com/',
    kind: 'html',
    sourceTier: 'official',
    isOfficial: true,
    limit: 8,
  },
  {
    topic: 'mobile',
    platform: 'android',
    name: 'Play Console Announcements',
    url: 'https://support.google.com/googleplay/android-developer/announcements/13412212?hl=en',
    kind: 'html',
    sourceTier: 'official',
    isOfficial: true,
    limit: 8,
  },
  {
    topic: 'mobile',
    platform: 'android',
    name: 'Android Developers Atom',
    url: 'https://android-developers.googleblog.com/feeds/posts/default?alt=rss',
    kind: 'rss',
    sourceTier: 'official-rss',
    isOfficial: true,
    limit: 8,
  },
  {
    topic: 'mobile',
    platform: 'cross',
    name: 'Google Developers Japan Atom',
    url: 'https://developers-jp.googleblog.com/feeds/posts/default?alt=rss',
    kind: 'rss',
    sourceTier: 'official-rss',
    isOfficial: true,
    limit: 8,
  },
  {
    topic: 'mobile',
    platform: 'android',
    name: 'Android Developers Japan Atom',
    url: 'https://android-developers-jp.googleblog.com/feeds/posts/default?alt=rss',
    kind: 'rss',
    sourceTier: 'official-rss',
    isOfficial: true,
    limit: 8,
  },
]
